# Generated by Django 2.2.6 on 2019-10-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgas', '0002_gasera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('placas', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('anio', models.IntegerField()),
                ('idGasera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Gasera')),
            ],
        ),
    ]
