# Generated by Django 2.2.6 on 2019-10-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgas', '0003_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosXEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGasera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Gasera')),
                ('idPedidosXEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.PedidosXEmpleado')),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Unidad')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgas.Pedido')),
            ],
        ),
    ]
